import type { Metadata } from "next";
import Footer from "../components/footer/page";
import Header from "../components/header/page";
import ProductsProvider from "../context/products-to-cart";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="flex flex-col min-h-screen">
                <ProductsProvider>
                    <>
                        <Header />
                        {children}
                        <Footer />
                    </>
                </ProductsProvider>
            </body>
        </html>
    );
}
